<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Licentia\Forms\Block\Form\Form $block */

/** @var \Licentia\Forms\Model\Forms $form */
$form = $block->getForm();

if (!$block->isEnabled()) {
    echo /* @noEscape */
    __('Form Not Available Anymore');

    return;
}

$elements = $form->getActiveElements();
/*
    <script type="text/javascript">
        require(['jquery'], function ($) {
            var pandaSubmitted = false;

            $('#panda-submit-form-<?= $form->getId() ?>').submit(function (event) {
                $('#panda-submit-form-<?= $form->getId() ?>')
                    .text('<?=  __('Please wait...') ?>');
                pandaSubmitted = true;
                //$('#form-<?= $form->getId() ?>').submit();
            });

            $(document).ajaxComplete(function () {
                if (pandaSubmitted === true) {
                    $('#panda-submit-form-<?= $form->getId() ?>')
                        .text('<?=  __(
                            $block->isEditing() ? $form->getUpdateLabel() : $form->getSubmitLabel()
                        ) ?>');
                }
            });
        });
    </script>
*/
?>

<?php if (!$block->canUserSubmit()): ?>

    <div class="message notice"><?= /* @noEscape */
        __(
            'Please <a href="%1">Login</a> to Submit Your Data',
            $block->getUrl('customer/account/login')
        ) ?></div>

<?php endif; ?>

<?php if ($block->canUserSubmit() === 2): ?>

    <div class="message notice"><?= /* @noEscape */
        __(
            '<a href="%1">Login</a> to view the form',
            $block->getUrl('customer/account/login')
        ) ?></div>

<?php endif; ?>


<?php if ($block->canUserSubmit() === true): ?>

    <form enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}' id="form-<?= /* @noEscape */
    $form->getId() ?>"
          class="panda form <?= /* @noEscape */
          $form->getData('css_class') ?>"
          action="<?= /* @noEscape */
          $block->getUrl('pandaf/form/save',
              ['form_id' => $form->getId(), '_secure' => true]) ?>"
          method="post">

        <?php if (!$form->getEnableTemplate()): ?>

            <fieldset class="fieldset">
                <legend class="legend"><span><?= /* @noEscape */
                        __($form->getTitle()) ?></span></legend>
                <br/>
                <div class="field note no-label"><?= /* @noEscape */
                    __($form->getDescription()) ?></div>
                <?php foreach ($elements as $element): ?>

                    <?= /* @noEscape */
                    $block->getElementHtml($element); ?>

                <?php endforeach; ?>

            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">

                    <?php if ($block->canUserSubmit()):

                        echo /* @noEscape */
                        $block->getSubmitButton();

                    endif; ?>

                </div>
            </div>
        <?php else: ?>

            <?= /* @noEscape */
            $block->parseTemplate() ?>

        <?php endif; ?>
    </form>

<?php endif; ?>

<?php if (!$block->canUserSubmit()): ?>

    <div class="message notice"><?= /* @noEscape */
        __(
            'Please <a href="%1">Login</a> to Submit Your Data',
            $block->getUrl('customer/account/login')
        ) ?></div>

<?php endif; ?>

